language: node_js
node_js:
  - "stable"

services:
  - "mongodb"
  - "docker"

before_script:
  - sleep 15
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose

script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - docker-compose up --build -d
  - cd labellab-server/
  - npm install
  - npm test
  - cd ../labellab-client
  - npm install
  - npm test
  - npm run build

after_script:
  - docker-compose down

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: labellab-client/build
  on:
    branch: master

branches:
  only:
  - gh-pages
  - /.*/
